### ISSUE TITLE
Add notification inbox

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#15]
As a user, I would like to see all notifications that have been sent to me in one inbox.
 The notification inbox lists all the user's messages in a preview. When you click on a message, it is displayed in full size.
Only one message can be displayed at a time in full size.

![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63072611/201526047-1850cd93-626b-49a6-9343-f8963a9a3286.png)
>
![Full HD](https://user-images.githubusercontent.com/63072611/201526862-1e3e577d-5f23-42e4-ab16-3cbb5b4f11f7.png)

### Definition of Done

- [ ] Each notification of the user is listed. The newest first.
- [ ] Notifications can be read by clicking on it. 
- [ ] Notifications can be permanently removed from the inbox.
- [ ] The notification inbox can be opened via the bell on the desktop home screen or the sidebar on the mobile version.

**Comment by bweengener** [comment]
Changelog:
- created base data model for messages (linked to user, display-flag to support remove-feature without actually deleting the record); https://github.com/hpi-swt2/bookkeeper-portal-red/commit/eee5c3ef07de1c4d2f466cee164abb1a5c03e358
- added UI: sidebar for desktop, full screen for mobile (can be triggered via bell-icon in navbar); https://github.com/hpi-swt2/bookkeeper-portal-red/commit/6e7885f0104198618ec3d3631980e5bf0c7fa4ce



![Image](https://user-images.githubusercontent.com/47246301/206041657-6b4ea6dc-d9ea-43ac-b13f-5d998ac14953.png)

----

![Image](https://user-images.githubusercontent.com/47246301/206041670-310bb3ad-1a32-4763-843b-b6a72a214a82.png)

**Comment by bweengener** [comment]
Proposed implementation:

![Image](https://user-images.githubusercontent.com/47246301/206818994-801b019f-8690-447b-ab04-4640408cb2f1.jpeg)

**Comment by bweengener** [comment]
Changelog:
- added rendering of visible notifications
- added support for deletion via DELETE-Endpoint (ApiController)

Open:
- Integration test of aforementioned flow (c.f. whiteboard draft)

@Raban (PO) This is ready for functional review.

CC: @Durborough , @gruendlich .

**Comment by Durborough** [comment]
Did the code review. See my comments there. I can help finish this on sunday. Is there still functionallity left to implement? Or just the I18n, Tests and some comments on why we did stuff like we did it?

**Comment by bweengener** [comment]
@Durborough 

> Did the code review. See my comments there. I can help finish this on sunday. Is there still functionallity left to implement?

No, only tests are missing. 

> Or just the I18n, Tests and some comments on why we did stuff like we did it?

Most of your comments are related to code that was not written by me. Coordinate how to fix them with @gruendlich, please.

**Comment by Durborough** [comment]
@Alorcus how should the notification side bar look, when there are no notifications? Does a mockup exist for that case?

**Comment by Alorcus** [comment]
A message like: "No new messages received" in the middle of the bar is enough.

**Comment by Durborough** [comment]
Changelog:

- Long messages are now shown with a short preview. Full messages can be read by clicking "+ read more"
- Expanded messages can be collapsed again by clicking "- read less"
- is the inbox empty, it says so instead of just showing nothing

TODO:

- internationalization of the collapsing buttons ("+ read more", "- read less". This might prove difficult since the corresponding strings are kept in the `notifications.scss` file.

**Comment by gruendlich** [comment]
Just noticed: When a clicking on "Show More" all notifications are expanded

**Comment by Durborough** [comment]
Changelog:

- Empty Inbox displays that it is empty
- Test for correctly rendered empty inbox
- Added Methods to send "Info", "Reminder" and "Alert" Notifactions, which creates the notifaction object and saves it in the database and optionally sends out a corresponding Email. Currently all Notification messages are the same, just differing in their subject and notification type in the database
- Test for sending a notifaction and it appearing in the inbox
- Clicking the "X" button on a Notification card now removes the card from the DOM instead of just hiding it
- Full Feature tests for removing a notifcation by clicking "X" in the notification card

**Comment by Durborough** [comment]
Somewhat an Issue:
Currently the removal test takes a little bit to long in our opinion:
The "Remove" button has JavaScript functionality to delete the notification card from the DOM and update the database entry. For testing we use Selenium. When we try to test if the card is removed immediately after clicking the button, it is not removed. However, when using "sleep 0.5" to wait before testing if the card is removed, it is removed. We believe this may have to do with concurrent processes. To us it is currently unclear how to avoid having to wait before testing. The waiting increases the overall test execution time from 0.02 seconds to 0.52 seconds on our machine.

**Comment by gruendlich** [comment]
Just noticed: We forgot to make the message "You have no notifications yet" use internationalization.
