### ISSUE TITLE
Fix validation for item creation

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swt2/bookkeeper-portal-red#152]
As an item owner I want to only be able to create items that pass a validation, especially an item must have
- a name
- a description
- a max borrowing days attribute
- a max reservation days attribute (that might be unnecessary, if a default value exists)

### Dependencies
- #9 

### Acceptance Criteria

- [ ] Items can only be created, if the owner inserted a name, description, max borrowing days and max reservation days
- [ ] Otherwise the item is not created and an appropriate warning is shown, if one of the mentioned attributes is missing

**Comment by richartkeil** [comment]
Estimate: S

**Comment by richartkeil** [comment]
Review by @johannaschlimme

**Comment by richartkeil** [comment]
@TimRiedel I just wanted to fix this, but I can't really reproduce the problem. The validation for items seems fails correctly, the logic for this exists since #46. The description does not have to be filled in, but I think that is intended. Did you mean something else, or did you perhaps still have an old version?

![Image](https://user-images.githubusercontent.com/8680858/210061578-603bd3e8-82c9-4e4a-988b-21b0d0a5fdb0.png)

**Comment by TimRiedel** [comment]
I think it might be fixed by now. We created this issue before #46 has been merged into dev.

**Comment by TimRiedel** [comment]
Maybe one idea would be to make the error message consistent with the other labels, e.g. the bar shown when an item is created, reserved, etc.
