### ISSUE TITLE
Set personal group as can_manage when creating an item

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#178]
As a user, I want to be able to edit the items I create.

### Dependencies

Depends on:

- #179 

### Acceptance Criteria

- [x]  When creating an item the personal group of the user creating it, gains can manage rights

**Comment by TimRiedel** [comment]
Hi, whats the status of the issue? Has there been any progress so far? Because in the interim presentation our PO wanted to show that managers of items can click on "Edit this item" and the other buttons, however that is not possible if user do not have personal groups with managing rights. Please see also my comment in issue #179, which explains the problem further.

**Comment by Alorcus** [comment]
Hey, what's the current status here? This is a Prio 1 ticket, would be great if the integration continues.

**Comment by TimRiedel** [comment]
Its ready for review now, we had a dependency on issue #179, which had to be completed first.
