### ISSUE TITLE
Ensure: Each User has and  is in a personal group

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#179]
As a User, I want a working permission system. Therefore, each user is in his own personal group, which allows rights management for individual users.

### Dependencies

Depends on:

- #20 

### Acceptance Criteria

- [x] The personal group is tagged with a label, so that it is communicated, that this is not a 'real' group
- [ ] Each user is in his/her personal group. (Attention to already existing users! Migrate DB if necessary)
- [x] If a new user sign up, he/she gets automatically added to his/her personal group.

**Comment by TimRiedel** [comment]
Hi, whats the status of this issue? I consider it of high importance, because if a user does not have a personal group the borrowing and reservation process will not work. It would have been nice to have this feature for the interim presentation, because in the upcoming deployment of the app (#205) we need to set the borrowing rights to `true` **for all users**, otherwise we can not present the mobile version of the app. However when setting it to `true` by default, we can not show that only users with the correct rights can borrow.

In PR #141 we used this code in the `create` method of the items controller, to temporarily create a default group, however this code is not pushed to dev and must be inserted manually every item:
```
unless Group.exists?(name: "Default Group")
    @testGroup = Group.new(name: "Default Group")
    @testGroup.save
end

@testGroup = Group.where(name: "Default Group").first
@testMembership = Membership.new(role: 1, user_id: current_user.id, group: @testGroup)
@testMembership.save
user_memberships = current_user.memberships
user_memberships.push(@testMembership)
current_user.save
item_groups = @item.borrower_groups
item_groups.push(@testGroup)
```
Is it possible for you to implement this issue before the interim presentation?
