### ISSUE TITLE
Restrict functionality of personal_groups

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#259]
As a user, I need a working permission system. The personal_group is required for a functioning authorization system. This group type has limited functionality to ensure a working permission system. It should not be possible to delete a personal group or add a new member to it.

Also, the 'group-management'-Page should hide the 'Add user' and 'Delete group' buttons: 
![grafik](https://user-images.githubusercontent.com/63072611/212270998-9fa8a650-1675-463e-83c2-68403c6e0bfd.png)

### Dependencies

Depends on:

- #6 
- #179 

### Acceptance Criteria

- [x]  It's not possible to add new members to a personal group.
- [x]  It's not possible to delete a personal group.
- [x] On the 'group management'-page of a personal group, the  'Add user' and 'Delete group' buttons are not displayed.

**Comment by Alorcus** [comment]
@TimRiedel @janiswehen @konrad-gerlach
You have integrated the personal groups. Am I right that you have also completed this task?

**Comment by TimRiedel** [comment]
Negative, I only added `can_manage`, `can_view` and `can_borrow` permissions to personal groups as can be seen in PR #283 and as far as I can see from the issue #179 of @janiswehen and @konrad-gerlach, they considered it to be purely a backend task. Backend-wise they implemented, that personal groups can only have one user, otherwise an error is thrown. The communication in PR #244 suggests, that the reviewer was aware, that the restricted functionality of personal groups is necessary, however this issue here was referenced as the solution to this problem.

**Comment by konrad-gerlach** [comment]
For deleting: Use https://stackoverflow.com/questions/123078/how-do-i-validate-on-destroy-in-rails

**Comment by konrad-gerlach** [comment]
For consistency's sake personal_groups are now automatically created after the user is created (not opt in anymore)

**Comment by konrad-gerlach** [comment]
User now can also not be in two personal_groups enforced by validation on memberships.

**Comment by konrad-gerlach** [comment]
It's not possible to add new members to a personal group. Was already implemented in #179

**Comment by konrad-gerlach** [comment]
https://stackoverflow.com/questions/2462203/rails-has-many-with-dynamic-conditions/20412163#20412163 for ensuring personal groups are dependents which are destroyed
