### ISSUE TITLE
Add item return overdue status and info

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#322]
As a user, I want to easily see when the borrowing period of an item I borrowed expired, so I get an urge to return the item as fast as possible. 

Therefore, the status batch of the item will say `overdue` (de: überfällig) and will be red.

Additionally, I will have an info box with `text1` in the style of #144 with a red border on the item details page. If there are multiple Info boxes getting rendered, this one should show up on top.

### Resources

`text1` (en): 
#### Return overdue. 
Your borrowing period has expired. Please return the item as soon as possible.

`text1` (de): 
#### Rückgabe überfällig
Ausleihzeit ist ausgelaufen. Bitte bringe das Item so schnell wie möglich zurück.

### Dependencies

Depends on:

- #8 

### Acceptance Criteria

When borrowing period is expired but item not yet returned:
- [x]  Status badge shows new  `overdue` status
- [x]  Info box with text1 is rendered

**Comment by Durborough** [comment]
**Changelog**
+ added overdue_for?(user) in the item model (The user has to be taken into account to avoid
+ added text for overdu item status in item model
+ added color red for item available status badge component if item is overdue for a person
+ added I18n for status badge overdue
+ Status badge shows new `overdue` status
+ fix: due_at field in item is now set correctly. This was accomplished by using `@item.max_borrowing_days` instead of `max_borrowing_days` during lending creation.

**Inportant** 
The order in which the status is checked in the item model and the status badge component is _important_. If changed this may result in bugs!

**Comment by Durborough** [comment]
**Changelog**
- fix: position of "Last seen at" Heading is now below the info boxes and above the map. This seems to make more sense, since the heading has nothing to do with the info boxes. #CollectiveCodeOwnership

**Comment by Durborough** [comment]
**Changelog**

- added Infobox if item is overdue for the current item
- changed the text and headline in the info box from the text requested in this ticket to fit the question-answer style of the other info boxes. @Alorcus is this fine?

**Comment by Durborough** [comment]
Pullrequest #358

**Comment by Durborough** [comment]
**Changelog**
- added tests for `overdue_for?(user)`

**Comment by Alorcus** [comment]
> **Changelog**
> 
>     * added Infobox with danger border color (red), if item is overdue for the current item
> 
>     * changed the text and headline in the info box from the text requested in this ticket to fit the question-answer style of the other info boxes. @Alorcus is this fine?

To decide this, I would like to see the actual UI. But overall I think this is fine @Durborough.
