### ISSUE TITLE
Introduce intermediate Permission model between Item and Group

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swt2/bookkeeper-portal-red#56]

**Comment by richartkeil** [comment]
Since #76 and #65 we change the initial plan of just referencing an `owner_group` and `access_group` on the item to instead introduce a many-to-many relationship for managing permissions.
There will now be a `Permission` model which can reference an `Item` and a `Group` and a type `can_manage`, `can_view`, `can_lend`.
