### ISSUE TITLE
Add parameter in the qr code

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#67]
As a dev, I want to be able to tell if a user is search this item site or came from the qr code. This has implications for the lending process.

### Dependencies

Depends on:

- #11

### Acceptance criteria

- [ ]  There is the parameter "src=qrcode" in the url after scanning the qr code 

### Storypoints
1

**Comment by richartkeil** [comment]
@DefineDan noticed that currently the "borrow" button won't be displayed after scanning a qrcode since the URL parameter provided and the one we check for (implemented in #99) don't match.
@FSadrieh Since it was in the acceptance criteria of this issue, could we re-open this (or open a new issue) so that the qrcode URL contains `src=qrcode` instead of `source=qrcode`?
