### ISSUE TITLE
Add history of items that I borrowed

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#68]
As a user I want to look up the hostory of items that I borrowed, so that

For Mock-Up scroll down (ignore the button "Me" next to "My analytics")

**Ignore the Column lender, because the current data model does not support an easy way of determining the owner of an item (see the discussion below)!!!** 
### Dependencies
- #42 
- #23 
- #11 
- #210 

### Acceptance Criteria
- [x] I see the history of borrowers, when I'm on the analytics screen
- [x] there is a button to switch to that exact history
- [x] Initially the History should include the item id and name, the name of the borrower and the borrowing period
- [x] clicking on the name/id should redirect to the item 
- [ ] clicking on the name of the borrower should redirect to the corresponding profile
- [x] style should mostly match the Mock-Up
- [x] history should be available in German and English
- [x] there is no column called lender

![Image](https://user-images.githubusercontent.com/66786380/211012617-36f79ba0-858b-4e14-b5ba-2ff23e307d6c.jpg)

**Comment by phkeese** [comment]
All items require a managing group consisting of multiple users, which user should be the "Lender" as shown in the mocks?

**Comment by Tonybodo** [comment]
One small note that should be considered. We already implement the opportunity for the owner to return the item himself. See #38
In our issue it is said, that the user who returned the item should be tracked in the lending history. Currently this is not possible with the current data model. Accordingly you are implement the lending history, can you ask your PO if this feature is necessary.  When you have discussed the problem and have come up with a solution, you can let me know.
In my opinion it does not make so much sense to track who the item returned, but when the customer really want to see this in the lending history we should implement it. The subsequent adaptation of the code for the owner return is not that difficult. You just have to add the line @lending.return_user = user or however you call the attribute then in the give_back method when the item is not borrowed from the current_user.

**Comment by Ngo-Tuan-Kiet** [comment]
So the problem would be, if we were to identify the lender by seeing who returned it because the owner could return it himself, and we don't want to display the owner as lender because that is obviously wrong? The problem would be fixed then if we just track the lender by seeing who borrowed it/started the lending period, right?

**Comment by Tonybodo** [comment]
Can you briefly describe how you use the term lender here? Lender means "Verleiher" and is not the person who borrow the item, that is the borrower. I know naming here can be a bit confusing. I As I understood we want to track the person who borrow the item and the person who click on the "return" button resp. the "as owner return" button. For that we have to expand the data model. The identification will not be the problem, because the current user who click the button is either the owner or the borrower and so the attribute in the expanded data model could be set on the current user. This does not affect the current attribute. So we probably need to split the user attribute into borrower and return_user or something. Perhaps @DefineDan can explain the client's intent in more detail.

**Comment by Ngo-Tuan-Kiet** [comment]
You are completely right, I thought we were talking about another issue (#63) and I got things mixed up 😅. So just ignore my first comment. Maybe there is just a small misunderstanding then. I basically equate "Lender" with "Owner". I just want to display who the item belongs to. And I just assumed that the database stored the owner of an item in some way.

**Comment by DefineDan** [comment]
> Can you briefly describe how you use the term lender here? Lender means "Verleiher" and is not the person who borrow the item, that is the borrower. I know naming here can be a bit confusing. I As I understood we want to track the person who borrow the item and the person who click on the "return" button resp. the "as owner return" button. For that we have to expand the data model. The identification will not be the problem, because the current user who click the button is either the owner or the borrower and so the attribute in the expanded data model could be set on the current user. This does not affect the current attribute. So we probably need to split the user attribute (which currently stands for the borrower) into borrower and return_user or something. Perhaps @DefineDan can explain the client's intent in more detail.

@Ngo-Tuan-Kiet  I think it's not trivial what to display for the lender with the current data model. Since we don't safe who created the item initially, the lender will be everyone that has can_manage rights for the item. That could be multiple groups. I have discussed with @FSadrieh whether to safe the initial creator of the item, but I think we didn't plan to do it for now.I guess either you implement this, find another creative solution, or just leave this column out for now.

What @Tonybodo was talking about is connected to this. If you wanted to display not only when you returned the item, but also by whom, you would have to track it somehow. Apparently, the data model does not do it at the moment, because it assumed the item will always be returned by the borrower himself. I suggest leaving this out for now, as you did in the wireframes, because the customer will barely recognize.

**Comment by Ngo-Tuan-Kiet** [comment]
I understand. I will revise this issue to just ignore the column then.
